### ISSUE TITLE
Mejora Clase DecimalCollection

### ISSUE THREAD

**Issue by b2lero** [b2lero/IWVG.SwC.XavierSotomayor#1]
[Más Información](https://github.com/b2lero/IWVG.SwC.XavierSotomayor/wiki/DecimalCollection#-ampliaciones-)

**Comment by b2lero** [comment]
No puedo seguir los commits que has hecho referidos a esta issue. Tenias que aver utilizado esta nomenclatura -- git commit -m " merge 'issue #1' into develop" --

**Comment by b2lero** [comment]
puedes referenciar por favor con un commit a este issue.

**Comment by L-Xinyu** [comment]
> No puedo seguir los commits que has hecho referidos a esta issue. Tenias que aver utilizado esta nomenclatura -- git commit -m " merge 'issue #1' into develop" --
Lo siento.Pero cada vez,cuando yo quiero merge a develop,hicelo como esto.
